releng/org.eclipse.papyrus.uml.diagram.sequence.releng/pom.xml
Fix the parent POM to run tests correctly on Mac.  Otherwise
they fail with SWT trying to initialize itself on the wrong
thread, Cocoa requiring the main thread.
Signed-off-by: Christian W. Damus <give.a.damus@gmail.com>
=> Build on Mac platform

.travis.yml, README.md
trivial commit to restore the behavior for metadata files, that should not have been overridden by commit from private repository.
=> TCI - restore metadata files as they were for the public repository

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/META-INF/MANIFEST.MF, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/Activator.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/parts/LifelineHeaderEditPart.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/InteractionLayoutEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/LifelineHeaderResizeEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/util/GeometryUtil.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/DefaultLayoutHelper.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/spi/LayoutHelper.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/META-INF/MANIFEST.MF, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/util/tests/GeometryUtilTest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/tests/matchers/GEFMatchers.java, tests/org.eclipse.papyrus.uml.interaction.graph.tests/META-INF/MANIFEST.MF, tests/org.eclipse.papyrus.uml.interaction.graph.tests/src/org/eclipse/papyrus/uml/interaction/tests/matchers/NotationMatchers.java, tests/org.eclipse.papyrus.uml.interaction.graph.tests/src/org/eclipse/papyrus/uml/interaction/tests/rules/ModelFixture.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/.classpath, tests/org.eclipse.papyrus.uml.interaction.model.tests/META-INF/MANIFEST.MF, tests/org.eclipse.papyrus.uml.interaction.model.tests/build.properties, tests/org.eclipse.papyrus.uml.interaction.model.tests/src-gen/org/eclipse/papyrus/uml/interaction/model/tests/SeqdAllTests.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/tests/DefaultLayoutHelperTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/tests/lifelines_layout.di, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/tests/lifelines_layout.notation, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/tests/lifelines_layout.uml, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/SeqDCustomTests.java
Add an API to the `LayoutHelper` to adjust proposed bounds for an existing shape in the diagram.  Use this new API to constrain the moving of lifeline headers to the horizontal dimension (including visual feed-back). Editing the size of a lifeline header likewise is constrained to the horizontal dimension (otherwise the lifeline body would be moved vertically).
The new `LayoutHelper` API and a few supporting utilities are covered with some simple JUnit tests.  Importantly, all of the `org.eclipse.papyrus.uml.interaction.{graph, model}` tests currently support stand-alone execution (without a running Eclipse platform), and I think we should maintain that.
However, there isn't yet any coverage of the edit policies, because we don't yet have an established pattern (there are currently no …
=> Fix #248 Lifeline Header

plugins/org.eclipse.papyrus.uml.interaction.model.edit/plugin.properties, plugins/org.eclipse.papyrus.uml.interaction.model.edit/src-gen/org/eclipse/papyrus/uml/interaction/model/provider/MElementItemProvider.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/LogicalModelPage.java, plugins/org.eclipse.papyrus.uml.interaction.model/META-INF/MANIFEST.MF, plugins/org.eclipse.papyrus.uml.interaction.model/model/seqd.genmodel, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/impl/InteractionModelBuilder.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/util/LogicalModelAdapter.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src-gen/org/eclipse/papyrus/uml/interaction/model/tests/SeqdAllTests.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/tests/LogicalModelAdapterTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/SeqDCustomTests.java
Implement linkage of the selection in the **Logical Model View** with the edit-part selection in the diagram editor.  This incidentally fixes a few problems:
- unnecessary preëmptive disposal of a new logical model
- attaching a new logical model to the UML `Interaction` before it has been initialized
=> Issue #295: Logical Model View Link Selection

plugins/org.eclipse.papyrus.uml.interaction.model.view/plugin.xml, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFEditPartPage.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFEditPartView.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFExplorerPage.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFExplorerPropertySource.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFExplorerUtils.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFExplorerView.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFFigurePage.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFFigureView.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFNotationPage.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/GMFNotationView.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/LogicalModelView.java, plugins/org.eclipse.papyrus.uml.interaction.model.view/src/org/eclipse/papyrus/uml/interaction/model/internal/view/PapyrusPageBookView.java
This pull request add three new views displaying the full hierarchy of the GEF Figures, the EditParts and the Views (GMF Notation model) of the current active GMF / Papyrus diagram.
All the views are synchronized with the GMF editor and supply a own implementation of a property sheet to display the values of the class fields, providing valuable information for debugging.
Most of the code from LogicalModelView is transfer to a generic view (PapyrusPageBookView). This new class is is extended by all the 4 views.
=> Extend #295: Figures, EditParts and Notation Views

plugins/org.eclipse.papyrus.uml.diagram.sequence.figure/src/org/eclipse/papyrus/uml/diagram/sequence/figure/LifelineBodyFigure.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.figure/src/org/eclipse/papyrus/uml/diagram/sequence/figure/RightArrowDecoration.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.figure/src/org/eclipse/papyrus/uml/diagram/sequence/figure/anchors/LifelineBodyAnchor.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/parts/GeneralOrderingEditPart.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/parts/LifelineBodyEditPart.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/ISequenceEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/InteractionLayoutEditPolicy.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/DefaultLayoutConstraints.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/spi/LayoutConstraints.java
Centralizes the magic numbers of figures, anchors & edit policies in the
layout
constraints.
The magic numbers of HeaderFigure are not included in this change. The class is curerntly not used and seems to be obsolete
Signed-off-by: Tobias Ortmayr <tortmayr.ext@eclipsesource.com>
=> Issue 308 -Migrate additional constants to layout constraints

plugins/org.eclipse.papyrus.uml.diagram.sequence.figure/src/org/eclipse/papyrus/uml/diagram/sequence/figure/LifelineBodyFigure.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.figure/src/org/eclipse/papyrus/uml/diagram/sequence/figure/anchors/LifelineBodyAnchor.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/parts/LifelineBodyEditPart.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/ISequenceEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/InteractionLayoutEditPolicy.java
Addresses review comments by Christian.
* Rename the anchor height property (and corresponding API Methods) to
anchor width
* Add getMinimumWidth() and getMinimumHeight methods to
ISequenceEditPoliy (similar to the ISequenceEditPart counterpart). This
enables the intended private use of the __getHostView() method
Signed-off-by: Tobias Ortmayr <tortmayr.ext@eclipsesource.com>
=> #308-Rename anchor height property & refactor ISequenceEditPolicy

releng/org.eclipse.papyrus.uml.diagram.sequence.targetplatform/org.eclipse.papyrus.uml.diagram.sequence.targetplatform.target, releng/org.eclipse.papyrus.uml.diagram.sequence.targetplatform/org.eclipse.papyrus.uml.diagram.sequence.targetplatform.tpd
This changes fixes a target content resolution issue for the "Sequence Diagram" target. Updates the repository location for the Eclipse Orbit project from an outdated (no longer existing) stable (S) repository to the recommended (R) repository for Oxygen.
=> Update Sequence Diagram target definition

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/InteractionLayoutEditPolicy.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/NudgeCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/NudgeHorizontallyCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/NudgeOnRemovalCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/ResizeHorizontallyCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/spi/NoopCommand.java
Introduce a `NoopCommand` as alternative to the `IdentityCommand` API that lets logical model commands compose themselves using the *pessimistic strict* `CompoundModelCommand`.  This ensures that in commands such as the `ResizeHorizontallyCommand`, chains beginning on the no-op will not lose the benefit of the strict compound that lets each command in sequence calculate its parameters on the basis of the results of the previous command.
A couple of points worth noting:
* we don't really need a `NoopCommand` type because we could just conventionally replace the `IdentityCommand` instead of chaining onto it in client code, but it's nice to have the consistency and fluency of chaining.  But that does mean that we need to remember to use the `NoopCommand` instead of `IdentityCommand` in all …
=> Lifeline resize: Ensure strict compound

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/META-INF/MANIFEST.MF, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/parts/MessageEditPart.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/AbstractSequenceGraphicalNodeEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/MessageEndpointEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/tools/DelegatingDragTracker.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/tools/MessageMoveTracker.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/util/CommandCreatedEvent.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/MessageMoveUITest.java
Ensure that the semantic re-ordering constraint on message ends is enforced on the moving of a message.  This includes display of the no-smoking cursor when such constraint would be violated.
=> Issue #38 Semantic constraint on move

plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/InsertExecutionCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/NudgeOnRemovalCommand.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/deletion/BasicDeletionTest.java
This PR is a proposal for updating the  behavior of insert/delete commands in the following manner
* Currently deletion preserves the space from first element after deletion to deleted element.
Elements after the deleted element are moved up b + c (i.e. space a is preserved)
This contradicts with the assumption that the space before an element belongs to the element (and not the one after it). This assumption has been specified by Antonio.
-> We propose moving up a+b (i.e. preserving space c)
a...space before deleted element
b...height of deleted element
c...space after deleted element to next element
* Currently we push everything down so that we at least have a  space after the inserted element.
Following the assumption of Antonio (Space before element belongs to element), we should -- …
=> Proposal for nudging behavior of insert/delete commands

plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/.classpath, plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/.project, plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/.settings/org.eclipse.jdt.core.prefs, plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/META-INF/MANIFEST.MF, plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/build.properties, plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/newchild/lightweight-seqd-newChild.creationmenumodel, plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/plugin.xml, plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/src/org/eclipse/papyrus/uml/diagram/sequence/contribution/simplifiedui/Activator.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/src/org/eclipse/papyrus/uml/diagram/sequence/contribution/simplifiedui/CreationMenuCleaner.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.contribution.simplifiedui/src/org/eclipse/papyrus/uml/diagram/sequence/contribution/simplifiedui/StartUp.java, plugins/pom.xml
This PR 
+ "customizes the New Child  menu in the property explorer as declared in #186 
+ adds a MenuCleaner to remove the "new Child"/"new Relationship" menus which are provided by PapyrusUML.
=> Disallow creation of fragments via model explorer #186

plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/InsertExecutionCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/NudgeOnRemovalCommand.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/SeqDCustomTests.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/creation/CreateExecutionTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/creation/CreateExecutionTesting.notation, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/creation/CreateExecutionTesting.uml, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/deletion/DeleteExecutionTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/deletion/DeleteExecutionTesting.notation, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/deletion/DeleteExecutionTesting.uml
This change addresses comment #343#issuecomment-418037298 (third
comment) of #343. When inserting an execution specification as first
element (execParams.isInsertBefore) of a lifeline, the isInsertBefore
flag has not been respected when invoking the nudge command.
=> Nudge also first element on insertion of execution #343

plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/InsertExecutionCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/InsertMessageCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/ModelCommand.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/MessageSnappingUITest.java, tests/org.eclipse.papyrus.uml.interaction.graph.tests/src/org/eclipse/papyrus/uml/interaction/tests/rules/ModelFixture.java
The insertion order of fragments depends on the kind of fragment being inserted, because the preferred semantic (time) ordering of fragments depends on the types of fragments.  Account for this explicitly in the creation of messages and execution specifications.
=> Fix issue #354: Fragment ordering

plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/InsertMessageCommand.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/SelfMessageCreationUITest.java
Prevent the drawing of a self-destruct message around an existing occurrence on the lifeline.
=> Fix #368 Self-destruct around occurrence

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/Activator.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/layout/DiagramFontHelper.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/impl/LogicalModelPlugin.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/DefaultFontHelper.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/DefaultLayoutConstraints.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/DefaultLayoutHelper.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/spi/FontHelper.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/spi/LayoutConstraints.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/spi/LayoutHelper.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/META-INF/MANIFEST.MF, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/DefaultLayoutHelperIntegrationUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/MessageMoveUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/MessageReconnectionConstraintsUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/MessageSnappingUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/kitchen-sink.di, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/kitchen-sink.notation, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/kitchen-sink.uml, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/tests/rules/EditorFixture.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src-gen/org/eclipse/papyrus/uml/interaction/model/tests/MExecutionOccurrenceTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src-gen/org/eclipse/papyrus/uml/interaction/model/tests/MExecutionTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src-gen/org/eclipse/papyrus/uml/interaction/model/tests/MLifelineTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src-gen/org/eclipse/papyrus/uml/interaction/model/tests/MMessageEndTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src-gen/org/eclipse/papyrus/uml/interaction/model/tests/MMessageTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/tests/DefaultLayoutHelperTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/creation/CreateMessageTestB.java
The *Logical Model* depends on a plugged-in `LayoutHelper` to determine X and Y positioning of notation views in the diagram without reference to the GEF presentation layer. However, this calculation is off by 3 in the Y direction and that error blocks testing of a fix for Issue #76.
So, add a temporary fudge factor to adjust the Y calculation by 3 until we can determine the root cause of the disparity and fix it properly.  Add a JUnit test that compares all computed Y values against actual GEF-rendered geometry for regression testing of this and a proper solution.
Other consequence updates to tests:
- can un-ignore a test that was ignored because of this Y error
- some layout test assertions have to be adjusted by 3
- other tests that create elements too close to other elements now are …
=> Issue #76: Adjust Y calculations in logical model

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/messages.properties, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/Messages.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/parts/LifelineNameEditPart.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/parsers/LifelineHeaderParser.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/providers/SequenceElementTypes.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/providers/SequenceParserProvider.java
Fix #247 by integrating the lifeline header label parser from Papyrus
Photon. This parser has mostly been added as is except for the following
fixes:
* Selector should always be enclosed in brackets
* Prevent new lines as not forseen in UML standard
=> Add parser for lifeline header label

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/InteractionLayoutEditPolicy.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/AddLifelineCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/DefaultLayoutConstraints.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/InteractionCreationEditPolicyUITest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/SeqDCustomTests.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/creation/padding/CreateLifelinePaddingTest.java
* Check if inserting on top of existing lifeline. if so, prevent overlap by moving self to the right
* In InteractionLayoutEditPolicy honour the x-position produced by the AddLifelineCommand, instead of forcing the mouse location in the editor
* Padding on move should be handled with issue #31 and issue #32
=> Issue #346: Horizontal padding of lifelines on creation

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/parts/LifelineHeaderEditPart.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/InteractionLayoutEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/LifelineHeaderResizeEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/tools/LifelineHeaderDragTracker.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/AddLifelineCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/DefaultLayoutConstraints.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/InteractionCreationEditPolicyUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/LifelineMoveUITest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/SeqDCustomTests.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/creation/padding/CreateLifelinePaddingTest.java
**This PR depends on https://github.com/eclipsesource/papyrus-seqd/pull/392** 
When no modifier key is pressed:
* only allow move of lifeline between its left and right neighbour while honouring padding constraints
* when moving further than our neighbours, move as far as possible
When modifier key is pressed:
* allow any move as before
* should include reorder logic (see issue #32)
=> Move Lifeline

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/LifelineHeaderResizeEditPolicy.java
This change refactores the implementation and introduce support for
preventing semantic changes during resize of lifeline header.
Enhances #393
=> Support resize in feedback and correction of command request

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/META-INF/MANIFEST.MF, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/parts/ExecutionSpecificationEditPart.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/ExecutionSpecificationDragEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/LifelineBodyDropEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/NoPapyrusEditPolicyProvider.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/PrivateRequestUtils.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/ResizableBorderItemPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/locators/OnLineBorderItemLocator.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/tools/SequenceDragTracker.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/DeferredPaddingCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/PendingVerticalExtentData.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/SetCoveredCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/SetOwnerCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/util/Optionals.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/ExecutionSpecificationDragEditPolicyUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/parsers/tests/MessageParserTest_PTest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/tests/rules/AutoFixture.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/tests/rules/AutoFixtureRule.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/tests/rules/ModelFixture.java, tests/org.eclipse.papyrus.uml.interaction.graph.tests/src/org/eclipse/papyrus/uml/interaction/tests/rules/ModelFixture.java
Implement support for grabbing an execution occurrence and
- sliding it up or down the lifeline, with or without the keyboard modifier for semantic re-ordering
- dropping it onto another lifeline, which requires the keyboard modifier for semantic re-ordering
=> Fix #70 Change lifeline covered by an execution specification

plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/SetCoveredCommand.java
When re-orienting a message that has an end being the start or finish of
an execution, this change also re-orients the opposite accordingly, so
that both eventually start/finish on the same lifeline.
With that, we ensure the validity of the following constraint:
If a reply message finishes the specification, this is, the finish
occurrence specification of the execution specification corresponds with
the send event message occurrence specification of the reply message,
the receive event of the message must be located in the same lifeline
than the send event of the message starting the execution specification,
if any.
Fix #42
=> Auto-correct lifeline of an executions' reply message

examples/LightweightSequenceExample/65-moving.notation, examples/LightweightSequenceExample/AnchorsModel.notation, plugins/org.eclipse.papyrus.uml.diagram.sequence.figure/src/org/eclipse/papyrus/uml/diagram/sequence/figure/ExecutionSpecificationFigure.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.figure/src/org/eclipse/papyrus/uml/diagram/sequence/figure/anchors/ExecutionSpecificationSideAnchor.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/AnchorFactory.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/65-moving.notation, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/ExecutionAnchorsUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/ExecutionMoveUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/execution-busy.notation, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/kitchen-sink.notation
- anchor now ignores the position on the notation, and only computes its
side  as it is done with start/finish anchors. A better solution may be
to only save height, and migrate all existing test models.
- add tests
=> 376 - Anchor position on executions

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/AbstractSequenceGraphicalNodeEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/ExecutionSpecificationDragEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/ISequenceEditPolicy.java, plugins/org.eclipse.papyrus.uml.interaction.model/src-gen/org/eclipse/papyrus/uml/interaction/internal/model/impl/MElementImpl.java, plugins/org.eclipse.papyrus.uml.interaction.model/src-gen/org/eclipse/papyrus/uml/interaction/internal/model/impl/MLifelineImpl.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/DeferredPaddingCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/InsertMessageCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/NudgeCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/SetLifelineCreationCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/spi/impl/DefaultLayoutHelper.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/creation/CreateMessageTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/creation/CreateMessageTestB.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/creation/CreateMessageTesting.notation
Re-use the command employed in re-targeting create messages for the initial create message scenario, too.  Also reuse the common deferred padding mechanism for the padding from the new lifeline head location.
In order to make the latter work, it is necessary also to fix a latent problem in which the duplicate calculation of commands
for the “unspecified type” create requests is trips up the dependency context’s tracking of unique command instances.
Also various problems in the handling of destruction occurrences in nudging.
=> Fix #385 Too much padding on create message

plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/InsertMessageCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/util/Executions.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/ExecutionAnchorsUITest.java
note: Based on branch for anchor positions fixes. The PR #405 should be reviewed first.
This modifies the computation of the potential execution spanning over the lifeline. So this should be compliant with nested executions, and this should also  fix the wrong anchor creation when inserting a message on the lifeline.
=> Issue #364 - Anchor position when inserting messages with nudging

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/ISequenceEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/MessageEndpointEditPolicy.java, plugins/org.eclipse.papyrus.uml.interaction.model/src-gen/org/eclipse/papyrus/uml/interaction/internal/model/impl/MElementImpl.java, plugins/org.eclipse.papyrus.uml.interaction.model/src-gen/org/eclipse/papyrus/uml/interaction/internal/model/impl/MInteractionImpl.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/DependencyContext.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/RootContextHandler.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/SortSemanticsCommand.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/FragmentReorder.di, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/FragmentReorder.notation, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/FragmentReorder.uml, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/FragmentReorderUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/tests/rules/AutoFixtureRule.java
Ensure that semantic reordering is always applied after all other changes, but still only once.  Do this by accumulating a deferred fragment sort command as we do a deferred padding command in the root dependency context, using a new RootContextHandler that provides the command handling that can be shared by both edit-policies and the model implementation.
Fixes #431 also.
=> Fix #427: Reordering of message ends

plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/NudgeCommand.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/SortSemanticsCommand.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/DeletionUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/tests/matchers/GEFMatchers.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/tests/rules/EditorFixture.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src-gen/org/eclipse/papyrus/uml/interaction/model/tests/MInteractionTest.java
Fix the failure of a nudge operation that isn’t needed for messages that are implicitly nudged by their attached
source and target views also being nudged, which is needlessly unexecutable.
Also fix the `SortSemanticsCommand` that sporadically fails on shuffles of the fragments that break the naïve
`MoveCommand` implementation.
=> Fix #439 Cannot delete a message

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/AbstractSequenceGraphicalNodeEditPolicy.java, plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/ISequenceEditPolicy.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/DependencyContext.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/tests/DependencyContextTest.java, tests/org.eclipse.papyrus.uml.interaction.model.tests/src/org/eclipse/papyrus/uml/interaction/model/tests/SeqDCustomTests.java
Implement context nesting to allow pre-calculation of multiple possible alternative operations, of which one is later selected and committed to the remainder of the computation.  Apply this nesting capability to the pop-up menu for sync messages.
=> Fix #429 Blank option in sync message menu

plugins/org.eclipse.papyrus.uml.diagram.sequence.runtime/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/AbstractSequenceGraphicalNodeEditPolicy.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/util/InteractionFragments.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/model/util/Optionals.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/META-INF/MANIFEST.MF, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/AbstractGraphicalEditPolicyUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/AsyncMessageNudgingUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/AsyncMessageReconnectionUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/AsyncMessages.di, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/AsyncMessages.notation, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/AsyncMessages.uml, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/AsyncMessages2.di, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/AsyncMessages2.notation, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/AsyncMessages2.uml, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/tests/rules/AutoFixtureRule.java
Fix the nudging of moving sloped messages up by ensuring that
- the moving of the source end computes a nudge from that end, and
- the a nudge computed by the receive end does not override the nudge computed by the source end when moving a message up
=> Fix #432 Nudging when moving sloped messages up

tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/DefaultLayoutHelperIntegrationUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/ExecutionSnappingUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/MessageMoveUITest.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/MessageSnappingUITest.java, tests/org.eclipse.papyrus.uml.interaction.graph.tests/META-INF/MANIFEST.MF, tests/org.eclipse.papyrus.uml.interaction.graph.tests/src/org/eclipse/papyrus/uml/interaction/tests/runners/Delegate.java, tests/org.eclipse.papyrus.uml.interaction.graph.tests/src/org/eclipse/papyrus/uml/interaction/tests/runners/FilterWith.java, tests/org.eclipse.papyrus.uml.interaction.graph.tests/src/org/eclipse/papyrus/uml/interaction/tests/runners/Filtered.java
Fix the skipping of the create-message moving tests added in an earlier pull request (at least, on Mac).
Also clean up the other six tests that have historically been skipping by just
- deleting tests that are no longer relevant (anti-requirements that were `@Ignore`d)
- filtering out tests in parameterized suites for combinations of parameters that don't make sense
The latter uses a new `Filtered` test runner implementation for self-filtering suites.
With these changes, we should now have **zero** skipped tests (and zero failures, of course) so that it will be easy to spot new assumption violations in the future.
=> Fix #437 Create-message moving tests skip

plugins/org.eclipse.papyrus.uml.interaction.graph/src/org/eclipse/papyrus/uml/interaction/graph/Tag.java, plugins/org.eclipse.papyrus.uml.interaction.graph/src/org/eclipse/papyrus/uml/interaction/internal/graph/GraphComputer.java, plugins/org.eclipse.papyrus.uml.interaction.graph/src/org/eclipse/papyrus/uml/interaction/internal/graph/TaggableImpl.java, plugins/org.eclipse.papyrus.uml.interaction.model/src/org/eclipse/papyrus/uml/interaction/internal/model/commands/NudgeCommand.java, tests/org.eclipse.papyrus.uml.diagram.sequence.runtime.tests/src/org/eclipse/papyrus/uml/diagram/sequence/runtime/internal/edit/policies/tests/NudgeRegressionUITest.java
Update the nudge command to account for the need to stretch up the top of the requesting execution when moving up an
execution started by it via a message.
=> Fix #453 Re-ordering when moving nested execution
